platform :ios , '8.0'
use_frameworks!

target 'EFTRLib' do
pod 'CocoaAsyncSocket', '~> 7.4.3'
pod 'Masonry', '~> 1.0.0'#autolayout 工具库 0.6.2
pod 'MJRefresh', '~> 3.1.0'#下拉刷新2.4.9
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'#计算cell高度
pod 'JHChainableAnimations', '~> 1.3.0'#便捷动画库
#pod 'AFNetworking', '~> 2.6.3'##EFWK
#pod 'MBProgressHUD', '~> 0.9.1'##EFWK
#pod 'OpenUDID', '~> 1.0.0'##EFWK
#pod 'FMDB', '~> 2.6'##EFWK
#pod 'CSStickyHeaderFlowLayout', '~> 0.2.9'#collection header
#pod 'StreamingKit', '~> 0.1.29'#音频流库
pod 'ZipArchive', '~> 1.4.0'#zip压缩、解压
pod 'Ono', '~> 1.2.2'#xml html解析库
#pod 'ZXingObjC', '~> 3.1.0'#一、二维码
#pod 'WebViewJavascriptBridge', '~> 4.1.4'
#pod 'pop', '~> 1.0.7'#facebook动画库
pod 'GPUImage', '~> 0.1.7'#图片滤镜、效果库
#pod 'RATreeView', '~> 1.0.3'#树状列表
#pod 'YmsCoreBluetooth', '~> 1.09.1'
#pod 'CardIO', '~> 5.3.1'#银行卡扫描
#pod 'TTTAttributedLabel', '~> 1.13.4'

pod 'Realm', '~> 0.102.0'#非关系型数据库
pod 'SDAutoLayout', '~> 1.53'
pod 'SDWebImage', '~> 3.7.6'

pod 'SDCycleScrollView','~> 1.64' #第一图片轮播器

pod 'iOS-MagnifyingGlass', '~> 0.0.2'#放大鏡

#pod 'TransitionTreasury', '~> 3.0.4'#转场动画
#pod 'TransitionAnimation', '~> 3.0.4'#转场动画依赖
# TTMAnimatedTransitionGallery


pod 'Permission', '~> 1.4.1'    #权限获取
#/*Bluetooth
#Camera
#Contacts
#Events
#Motion
#Microphone
#Notifications
#Photos
#Reminders
#LocationAlways
#LocationWhenInUse*/

pod 'SYStickHeaderWaterFall', '~> 0.0.2' #瀑布流

pod 'TextFieldEffects', '~> 1.2.0' #魔法输入框，各自样式

end