platform :ios , '8.0'
use_frameworks!

pod 'AFNetworking', '~> 2.6.3'
#pod 'CocoaAsyncSocket', '~> 7.4.3'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'OpenUDID', '~> 1.0.0'
pod 'FMDB', '~> 2.6'
##pod 'ZXingObjC', '~> 3.1.0'#一、二维码
#pod 'ZipArchive', '~> 1.4.0'#zip压缩、解压
##pod 'WebViewJavascriptBridge', '~> 4.1.4'
#pod 'Masonry', '~> 0.6.4'#autolayout 工具库 0.6.2
#pod 'Ono', '~> 1.2.2'#xml html解析库
##pod 'pop', '~> 1.0.7'#facebook动画库
##pod 'GPUImage', '~> 0.1.6'#图片滤镜、效果库
#pod 'MJRefresh', '~> 3.1.0'#下拉刷新2.4.9
##pod 'RATreeView', '~> 1.0.3'#树状列表
#pod 'CSStickyHeaderFlowLayout', '~> 0.2.9'#collection header
#pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'#计算cell高度
#pod 'JHChainableAnimations', '~> 1.3.0'#便捷动画库
##pod 'YmsCoreBluetooth', '~> 1.09.1'
##pod 'CardIO', '~> 5.3.1'#银行卡扫描
##pod 'TTTAttributedLabel', '~> 1.13.4'
#pod 'StreamingKit', '~> 0.1.29'
